### PR TITLE
Patch for #16 - remove encode calls, instead use properly encoded conten...

### PR DESCRIPTION
**Pull request by ppawel**
...t of HTTP responses.

### CODE REVIEW

**Comment by ppawel** [comment]
Looking at the Python Requests documentation it seems that it should work properly with r.text [1].

In any case I would recommend that the API (getWay, getNode etc.) assumes that unicode objects are returned - so changemonger.py does not do encode calls. This makes it easier to reimplement the API.

[1] http://docs.python-requests.org/en/latest/user/quickstart/#response-content

**Comment by ppawel** [comment]
Hmm, it's strange because it DOES NOT seem to be working as stated in the documentation... r.text in osmapi.py is always a str object, not an unicode object so obviously there are problems with encoding later on. r.encoding states "utf-8" so I would expect that r.text returns proper unicode object...

**Comment by emacsen** [comment]
See https://github.com/emacsen/changemonger/issues/8

The code you're seeing was patched in to address issues with XML encoding issues.

I am hesitant to touch this code now, and do not see what harm explicit unicode encoding does.

**Comment by ppawel** [comment]
#8 is fixed with my code as well... It's about having a clear contract between API and core Changemonger - instead of having to encode it to UTF-8 everywhere in your code, you assume you get unicode objects which is not a problem since HTTP libraries and database access libraries (like pyscopg2 that I'm using) all offer unicode object as output.

But ultimately it's your decision... so just let me know, I will need to think what to do next with my branch.

**Comment by samatjain** [comment]
python-requests is fine; lxml isn't (personally, I do not understand why).

See https://github.com/samatjain/changemonger/commit/ccf9b1f21dd833131ae208399a9cc2af92f57c53; lxml takes a Unicode string and internally converts it back to ascii, which fails (see issue #8) when the Unicode string _isn't_ ascii.

**Pull request closed without merging**
